export const RESERVATION_EVENT_GATE_IDS = Object.freeze({
  RECEIVER_EVENT_TYPE: 'ops.reservation_event.receiver.event_type',
  RECEIVER_EVENT_ID: 'ops.reservation_event.receiver.event_id',
  RECEIVER_BODY_IDENTITY: 'ops.reservation_event.receiver.body_identity',
  RECEIVER_CREATED_PAYLOAD: 'ops.reservation_event.receiver.created_payload',
  RECEIVER_CANCELLED_PAYLOAD: 'ops.reservation_event.receiver.cancelled_payload',
  SOURCE_PROVIDER_COMPATIBILITY: 'ops.reservation_event.source.provider_compatibility',
  IMS_BINDING_BEFORE_PROJECTION: 'ops.reservation_event.ims.binding_before_projection',
  IMS_BINDING_AVAILABILITY: 'ops.reservation_event.ims.binding_availability',
  OPS_PROJECTION_IDENTITY: 'ops.reservation_event.ops.projection_identity',
});

export const reservationEventGateCatalog = Object.freeze([
  {
    id: RESERVATION_EVENT_GATE_IDS.RECEIVER_EVENT_TYPE,
    category: 'receiver',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'Reservation event receiver accepts only reservation.created and reservation.cancelled.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.RECEIVER_EVENT_ID,
    category: 'receiver',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'Reservation event receiver requires an event id before storage or import.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.RECEIVER_BODY_IDENTITY,
    category: 'receiver',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'Header and body event id/type must match when body fields are present.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.RECEIVER_CREATED_PAYLOAD,
    category: 'receiver',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'Created events require a booking object and at least one reservation identity.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.RECEIVER_CANCELLED_PAYLOAD,
    category: 'receiver',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'Cancelled events require provider and source reservation id for manual review intake.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.SOURCE_PROVIDER_COMPATIBILITY,
    category: 'source',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/homepage-reservation-mapper.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'Source provider normalization preserves the current implicit homepage fallback.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.IMS_BINDING_BEFORE_PROJECTION,
    category: 'ims',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'OPS projection waits for existing IMS binding, IMS partner binding, or IMS create/reuse success.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.IMS_BINDING_AVAILABILITY,
    category: 'ims',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'A linked IMS external reservation id must not already belong to another OPS reservation.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
  {
    id: RESERVATION_EVENT_GATE_IDS.OPS_PROJECTION_IDENTITY,
    category: 'ops_projection',
    owner: 'ops',
    sourcePath: 'reservation_ai_parser/src/server.js',
    helperPath: 'reservation_ai_parser/gates/reservation-event-gates.js',
    description: 'OPS projection requires both OPS reservation id and reservation ref id.',
    runtimeBehavior: 'preserve',
    protectedTargets: [],
  },
]);

export function listReservationEventGateIds() {
  return reservationEventGateCatalog.map((gate) => gate.id);
}
